FROM rust:latest as builder
RUN apt-get update && \
    apt-get install -y protobuf-compiler
WORKDIR /app
COPY . .
RUN cargo build --workspace --release --bin client

FROM debian:bullseye
WORKDIR /app
COPY --from=builder /app/target/release/client .
ENTRYPOINT ["./client"]
