apiVersion: v1
kind: Service
metadata:
  name: kv-server
  labels:
    app: kv-server
spec:
  ports:
  - port: 5000
    name: kv-server
  clusterIP: None
  selector:
    app: kv-server

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kv-server
spec:
  selector:
    matchLabels:
      app: kv-server
  serviceName: "kv-server"
  replicas: 5
  template:
    metadata:
      labels:
        app: kv-server
    spec:
      containers:
      - name: kv-server
        image: gitlab.lrz.de
        ports:
          - containerPort: 5551
          - containerPort: 5144
          - containerPort: 5145
          - containerPort: 5146
          - containerPort: 5147
        command:
          - bash
          - "-c"
          - ./run-server-k8s.sh -r 1 -w 1 -f 3 -a $(hostname).kv-server.default.svc.cluster.local -x $(hostname) -b $(hostname).kv-server.default.svc.cluster.local:5144
