[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
prost = "0.11"
prost-types = "0.11"
tonic = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"
